/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as SchoolsSlugRouteImport } from './routes/schools.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as NewsletterUnsubscribeRouteImport } from './routes/newsletter.unsubscribe'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BundleSlugRouteImport } from './routes/bundle.$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ShopCategoryIndexRouteImport } from './routes/shop.$category.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as ShopCategorySubcategoryRouteImport } from './routes/shop.$category.$subcategory'
import { Route as CheckoutSuccessOrderNumberRouteImport } from './routes/checkout.success.$orderNumber'
import { Route as ApiCronSalesCountsRouteImport } from './routes/api/cron.sales-counts'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron.reminders'
import { Route as AuthenticatedAccountWishlistRouteImport } from './routes/_authenticated/account.wishlist'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AuthenticatedAccountNotificationsRouteImport } from './routes/_authenticated/account.notifications'
import { Route as AuthenticatedAccountAddressesRouteImport } from './routes/_authenticated/account.addresses'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminSchoolsRouteImport } from './routes/_admin/admin.schools'
import { Route as AdminAdminSchoolBundlesRouteImport } from './routes/_admin/admin.school-bundles'
import { Route as AdminAdminReviewsRouteImport } from './routes/_admin/admin.reviews'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin/admin.reports'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin/admin.products'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin.orders'
import { Route as AdminAdminMessagesRouteImport } from './routes/_admin/admin.messages'
import { Route as AdminAdminMarketingRouteImport } from './routes/_admin/admin.marketing'
import { Route as AdminAdminLogsRouteImport } from './routes/_admin/admin.logs'
import { Route as AdminAdminHomepageRouteImport } from './routes/_admin/admin.homepage'
import { Route as AdminAdminCustomersRouteImport } from './routes/_admin/admin.customers'
import { Route as AdminAdminCouponsRouteImport } from './routes/_admin/admin.coupons'
import { Route as AdminAdminCategoriesRouteImport } from './routes/_admin/admin.categories'
import { Route as AdminAdminBundlesRouteImport } from './routes/_admin/admin.bundles'
import { Route as AdminAdminBannersRouteImport } from './routes/_admin/admin.banners'
import { Route as AdminAdminAttributesRouteImport } from './routes/_admin/admin.attributes'
import { Route as ApiPaymentsProviderCallbackRouteImport } from './routes/api/payments.$provider.callback'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsSlugRoute = SchoolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SchoolsRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterUnsubscribeRoute = NewsletterUnsubscribeRouteImport.update({
  id: '/newsletter/unsubscribe',
  path: '/newsletter/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleSlugRoute = BundleSlugRouteImport.update({
  id: '/bundle/$slug',
  path: '/bundle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryIndexRoute = ShopCategoryIndexRouteImport.update({
  id: '/shop/$category/',
  path: '/shop/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ShopCategorySubcategoryRoute = ShopCategorySubcategoryRouteImport.update({
  id: '/shop/$category/$subcategory',
  path: '/shop/$category/$subcategory',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessOrderNumberRoute =
  CheckoutSuccessOrderNumberRouteImport.update({
    id: '/success/$orderNumber',
    path: '/success/$orderNumber',
    getParentRoute: () => CheckoutRoute,
  } as any)
const ApiCronSalesCountsRoute = ApiCronSalesCountsRouteImport.update({
  id: '/api/cron/sales-counts',
  path: '/api/cron/sales-counts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountWishlistRoute =
  AuthenticatedAccountWishlistRouteImport.update({
    id: '/account/wishlist',
    path: '/account/wishlist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/account/orders',
    path: '/account/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountNotificationsRoute =
  AuthenticatedAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountAddressesRoute =
  AuthenticatedAccountAddressesRouteImport.update({
    id: '/account/addresses',
    path: '/account/addresses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSchoolsRoute = AdminAdminSchoolsRouteImport.update({
  id: '/admin/schools',
  path: '/admin/schools',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminSchoolBundlesRoute = AdminAdminSchoolBundlesRouteImport.update({
  id: '/admin/school-bundles',
  path: '/admin/school-bundles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminReviewsRoute = AdminAdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminMessagesRoute = AdminAdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminMarketingRoute = AdminAdminMarketingRouteImport.update({
  id: '/admin/marketing',
  path: '/admin/marketing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminLogsRoute = AdminAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminHomepageRoute = AdminAdminHomepageRouteImport.update({
  id: '/admin/homepage',
  path: '/admin/homepage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminCustomersRoute = AdminAdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminCouponsRoute = AdminAdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminCategoriesRoute = AdminAdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminBundlesRoute = AdminAdminBundlesRouteImport.update({
  id: '/admin/bundles',
  path: '/admin/bundles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminBannersRoute = AdminAdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminAttributesRoute = AdminAdminAttributesRouteImport.update({
  id: '/admin/attributes',
  path: '/admin/attributes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPaymentsProviderCallbackRoute =
  ApiPaymentsProviderCallbackRouteImport.update({
    id: '/api/payments/$provider/callback',
    path: '/api/payments/$provider/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/schools': typeof SchoolsRouteWithChildren
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/schools/$slug': typeof SchoolsSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/attributes': typeof AdminAdminAttributesRoute
  '/admin/banners': typeof AdminAdminBannersRoute
  '/admin/bundles': typeof AdminAdminBundlesRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/homepage': typeof AdminAdminHomepageRoute
  '/admin/logs': typeof AdminAdminLogsRoute
  '/admin/marketing': typeof AdminAdminMarketingRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/school-bundles': typeof AdminAdminSchoolBundlesRoute
  '/admin/schools': typeof AdminAdminSchoolsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/cron/sales-counts': typeof ApiCronSalesCountsRoute
  '/checkout/success/$orderNumber': typeof CheckoutSuccessOrderNumberRoute
  '/shop/$category/$subcategory': typeof ShopCategorySubcategoryRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/shop/$category/': typeof ShopCategoryIndexRoute
  '/api/payments/$provider/callback': typeof ApiPaymentsProviderCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/schools': typeof SchoolsRouteWithChildren
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/schools/$slug': typeof SchoolsSlugRoute
  '/shop': typeof ShopIndexRoute
  '/admin/attributes': typeof AdminAdminAttributesRoute
  '/admin/banners': typeof AdminAdminBannersRoute
  '/admin/bundles': typeof AdminAdminBundlesRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/homepage': typeof AdminAdminHomepageRoute
  '/admin/logs': typeof AdminAdminLogsRoute
  '/admin/marketing': typeof AdminAdminMarketingRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/school-bundles': typeof AdminAdminSchoolBundlesRoute
  '/admin/schools': typeof AdminAdminSchoolsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/cron/sales-counts': typeof ApiCronSalesCountsRoute
  '/checkout/success/$orderNumber': typeof CheckoutSuccessOrderNumberRoute
  '/shop/$category/$subcategory': typeof ShopCategorySubcategoryRoute
  '/admin': typeof AdminAdminIndexRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/shop/$category': typeof ShopCategoryIndexRoute
  '/api/payments/$provider/callback': typeof ApiPaymentsProviderCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/schools': typeof SchoolsRouteWithChildren
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/bundle/$slug': typeof BundleSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/schools/$slug': typeof SchoolsSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/_admin/admin/attributes': typeof AdminAdminAttributesRoute
  '/_admin/admin/banners': typeof AdminAdminBannersRoute
  '/_admin/admin/bundles': typeof AdminAdminBundlesRoute
  '/_admin/admin/categories': typeof AdminAdminCategoriesRoute
  '/_admin/admin/coupons': typeof AdminAdminCouponsRoute
  '/_admin/admin/customers': typeof AdminAdminCustomersRoute
  '/_admin/admin/homepage': typeof AdminAdminHomepageRoute
  '/_admin/admin/logs': typeof AdminAdminLogsRoute
  '/_admin/admin/marketing': typeof AdminAdminMarketingRoute
  '/_admin/admin/messages': typeof AdminAdminMessagesRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/products': typeof AdminAdminProductsRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/reviews': typeof AdminAdminReviewsRoute
  '/_admin/admin/school-bundles': typeof AdminAdminSchoolBundlesRoute
  '/_admin/admin/schools': typeof AdminAdminSchoolsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_authenticated/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/_authenticated/account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/_authenticated/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/cron/sales-counts': typeof ApiCronSalesCountsRoute
  '/checkout/success/$orderNumber': typeof CheckoutSuccessOrderNumberRoute
  '/shop/$category/$subcategory': typeof ShopCategorySubcategoryRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/shop/$category/': typeof ShopCategoryIndexRoute
  '/api/payments/$provider/callback': typeof ApiPaymentsProviderCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/refund'
    | '/robots.txt'
    | '/schools'
    | '/search'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/admin/login'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/bundle/$slug'
    | '/category/$slug'
    | '/newsletter/unsubscribe'
    | '/product/$slug'
    | '/schools/$slug'
    | '/shop/'
    | '/admin/attributes'
    | '/admin/banners'
    | '/admin/bundles'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/homepage'
    | '/admin/logs'
    | '/admin/marketing'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/school-bundles'
    | '/admin/schools'
    | '/admin/settings'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/orders'
    | '/account/wishlist'
    | '/api/cron/reminders'
    | '/api/cron/sales-counts'
    | '/checkout/success/$orderNumber'
    | '/shop/$category/$subcategory'
    | '/admin/'
    | '/account/'
    | '/shop/$category/'
    | '/api/payments/$provider/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/refund'
    | '/robots.txt'
    | '/schools'
    | '/search'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/admin/login'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/bundle/$slug'
    | '/category/$slug'
    | '/newsletter/unsubscribe'
    | '/product/$slug'
    | '/schools/$slug'
    | '/shop'
    | '/admin/attributes'
    | '/admin/banners'
    | '/admin/bundles'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/homepage'
    | '/admin/logs'
    | '/admin/marketing'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/school-bundles'
    | '/admin/schools'
    | '/admin/settings'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/orders'
    | '/account/wishlist'
    | '/api/cron/reminders'
    | '/api/cron/sales-counts'
    | '/checkout/success/$orderNumber'
    | '/shop/$category/$subcategory'
    | '/admin'
    | '/account'
    | '/shop/$category'
    | '/api/payments/$provider/callback'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/refund'
    | '/robots.txt'
    | '/schools'
    | '/search'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/admin/login'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/bundle/$slug'
    | '/category/$slug'
    | '/newsletter/unsubscribe'
    | '/product/$slug'
    | '/schools/$slug'
    | '/shop/'
    | '/_admin/admin/attributes'
    | '/_admin/admin/banners'
    | '/_admin/admin/bundles'
    | '/_admin/admin/categories'
    | '/_admin/admin/coupons'
    | '/_admin/admin/customers'
    | '/_admin/admin/homepage'
    | '/_admin/admin/logs'
    | '/_admin/admin/marketing'
    | '/_admin/admin/messages'
    | '/_admin/admin/orders'
    | '/_admin/admin/products'
    | '/_admin/admin/reports'
    | '/_admin/admin/reviews'
    | '/_admin/admin/school-bundles'
    | '/_admin/admin/schools'
    | '/_admin/admin/settings'
    | '/_authenticated/account/addresses'
    | '/_authenticated/account/notifications'
    | '/_authenticated/account/orders'
    | '/_authenticated/account/wishlist'
    | '/api/cron/reminders'
    | '/api/cron/sales-counts'
    | '/checkout/success/$orderNumber'
    | '/shop/$category/$subcategory'
    | '/_admin/admin/'
    | '/_authenticated/account/'
    | '/shop/$category/'
    | '/api/payments/$provider/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  RefundRoute: typeof RefundRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SchoolsRoute: typeof SchoolsRouteWithChildren
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  BundleSlugRoute: typeof BundleSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  NewsletterUnsubscribeRoute: typeof NewsletterUnsubscribeRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiCronSalesCountsRoute: typeof ApiCronSalesCountsRoute
  ShopCategorySubcategoryRoute: typeof ShopCategorySubcategoryRoute
  ShopCategoryIndexRoute: typeof ShopCategoryIndexRoute
  ApiPaymentsProviderCallbackRoute: typeof ApiPaymentsProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/$slug': {
      id: '/schools/$slug'
      path: '/$slug'
      fullPath: '/schools/$slug'
      preLoaderRoute: typeof SchoolsSlugRouteImport
      parentRoute: typeof SchoolsRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/unsubscribe': {
      id: '/newsletter/unsubscribe'
      path: '/newsletter/unsubscribe'
      fullPath: '/newsletter/unsubscribe'
      preLoaderRoute: typeof NewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle/$slug': {
      id: '/bundle/$slug'
      path: '/bundle/$slug'
      fullPath: '/bundle/$slug'
      preLoaderRoute: typeof BundleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category/': {
      id: '/shop/$category/'
      path: '/shop/$category'
      fullPath: '/shop/$category/'
      preLoaderRoute: typeof ShopCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/shop/$category/$subcategory': {
      id: '/shop/$category/$subcategory'
      path: '/shop/$category/$subcategory'
      fullPath: '/shop/$category/$subcategory'
      preLoaderRoute: typeof ShopCategorySubcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success/$orderNumber': {
      id: '/checkout/success/$orderNumber'
      path: '/success/$orderNumber'
      fullPath: '/checkout/success/$orderNumber'
      preLoaderRoute: typeof CheckoutSuccessOrderNumberRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/cron/sales-counts': {
      id: '/api/cron/sales-counts'
      path: '/api/cron/sales-counts'
      fullPath: '/api/cron/sales-counts'
      preLoaderRoute: typeof ApiCronSalesCountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/wishlist': {
      id: '/_authenticated/account/wishlist'
      path: '/account/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AuthenticatedAccountWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/notifications': {
      id: '/_authenticated/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/addresses': {
      id: '/_authenticated/account/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AuthenticatedAccountAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/schools': {
      id: '/_admin/admin/schools'
      path: '/admin/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminAdminSchoolsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/school-bundles': {
      id: '/_admin/admin/school-bundles'
      path: '/admin/school-bundles'
      fullPath: '/admin/school-bundles'
      preLoaderRoute: typeof AdminAdminSchoolBundlesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/reviews': {
      id: '/_admin/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminAdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/messages': {
      id: '/_admin/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/marketing': {
      id: '/_admin/admin/marketing'
      path: '/admin/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminAdminMarketingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/logs': {
      id: '/_admin/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminAdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/homepage': {
      id: '/_admin/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminAdminHomepageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/customers': {
      id: '/_admin/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminAdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/coupons': {
      id: '/_admin/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminAdminCouponsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/categories': {
      id: '/_admin/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/bundles': {
      id: '/_admin/admin/bundles'
      path: '/admin/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AdminAdminBundlesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/banners': {
      id: '/_admin/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminAdminBannersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/attributes': {
      id: '/_admin/admin/attributes'
      path: '/admin/attributes'
      fullPath: '/admin/attributes'
      preLoaderRoute: typeof AdminAdminAttributesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/payments/$provider/callback': {
      id: '/api/payments/$provider/callback'
      path: '/api/payments/$provider/callback'
      fullPath: '/api/payments/$provider/callback'
      preLoaderRoute: typeof ApiPaymentsProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminAttributesRoute: typeof AdminAdminAttributesRoute
  AdminAdminBannersRoute: typeof AdminAdminBannersRoute
  AdminAdminBundlesRoute: typeof AdminAdminBundlesRoute
  AdminAdminCategoriesRoute: typeof AdminAdminCategoriesRoute
  AdminAdminCouponsRoute: typeof AdminAdminCouponsRoute
  AdminAdminCustomersRoute: typeof AdminAdminCustomersRoute
  AdminAdminHomepageRoute: typeof AdminAdminHomepageRoute
  AdminAdminLogsRoute: typeof AdminAdminLogsRoute
  AdminAdminMarketingRoute: typeof AdminAdminMarketingRoute
  AdminAdminMessagesRoute: typeof AdminAdminMessagesRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminProductsRoute: typeof AdminAdminProductsRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminReviewsRoute: typeof AdminAdminReviewsRoute
  AdminAdminSchoolBundlesRoute: typeof AdminAdminSchoolBundlesRoute
  AdminAdminSchoolsRoute: typeof AdminAdminSchoolsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminAttributesRoute: AdminAdminAttributesRoute,
  AdminAdminBannersRoute: AdminAdminBannersRoute,
  AdminAdminBundlesRoute: AdminAdminBundlesRoute,
  AdminAdminCategoriesRoute: AdminAdminCategoriesRoute,
  AdminAdminCouponsRoute: AdminAdminCouponsRoute,
  AdminAdminCustomersRoute: AdminAdminCustomersRoute,
  AdminAdminHomepageRoute: AdminAdminHomepageRoute,
  AdminAdminLogsRoute: AdminAdminLogsRoute,
  AdminAdminMarketingRoute: AdminAdminMarketingRoute,
  AdminAdminMessagesRoute: AdminAdminMessagesRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminProductsRoute: AdminAdminProductsRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminReviewsRoute: AdminAdminReviewsRoute,
  AdminAdminSchoolBundlesRoute: AdminAdminSchoolBundlesRoute,
  AdminAdminSchoolsRoute: AdminAdminSchoolsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountAddressesRoute: typeof AuthenticatedAccountAddressesRoute
  AuthenticatedAccountNotificationsRoute: typeof AuthenticatedAccountNotificationsRoute
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
  AuthenticatedAccountWishlistRoute: typeof AuthenticatedAccountWishlistRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountAddressesRoute: AuthenticatedAccountAddressesRoute,
  AuthenticatedAccountNotificationsRoute:
    AuthenticatedAccountNotificationsRoute,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
  AuthenticatedAccountWishlistRoute: AuthenticatedAccountWishlistRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessOrderNumberRoute: typeof CheckoutSuccessOrderNumberRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessOrderNumberRoute: CheckoutSuccessOrderNumberRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface SchoolsRouteChildren {
  SchoolsSlugRoute: typeof SchoolsSlugRoute
}

const SchoolsRouteChildren: SchoolsRouteChildren = {
  SchoolsSlugRoute: SchoolsSlugRoute,
}

const SchoolsRouteWithChildren =
  SchoolsRoute._addFileChildren(SchoolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  RefundRoute: RefundRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SchoolsRoute: SchoolsRouteWithChildren,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  BundleSlugRoute: BundleSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  NewsletterUnsubscribeRoute: NewsletterUnsubscribeRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiCronSalesCountsRoute: ApiCronSalesCountsRoute,
  ShopCategorySubcategoryRoute: ShopCategorySubcategoryRoute,
  ShopCategoryIndexRoute: ShopCategoryIndexRoute,
  ApiPaymentsProviderCallbackRoute: ApiPaymentsProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
